In [9]:
draw_commit_graph_cpp('git-playground')

09ac13e7898a95ff040852a4eb8914fea0b77112: A
eb0791ddaa0b12e701a5ad781c2fe91296d404d9: A R
a8eb2e44a4227d10d0f25bc3329466bd4b6992ab: M A
d9e049b2ff4e8da0575fd83295091141dba1c840: D A
2bbe0aa7322a7360003ba06130a6815be34e49f0: D A
3d341d435b5ceee208858d247d7507e68270aae2: R


In [1]:
from ruby_commit_graph import draw_commit_graph_ruby
draw_commit_graph_ruby('audience1st', 200)

7f3e6254389aa07464803da1a0557e629dda8507: A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A 

In [2]:
from cpp_commit_graph import draw_commit_graph_cpp
draw_commit_graph_cpp('Sexain-MemController')

83d7c66a8df18890925076110ea0f3e96828e3fb: A A A
912cb208f9f4b2ca9e7214add915f69f3bcf2f52: A A
583dd4cc1fe72c25a1e17bf1644f113e8fc6d2fc: M M
0cb945d1939eb62eb41e5cae000287402d57f599: M M
fa0ea5672f7e8d6331e06e30ad93ef1a4245cb7f: M R
ac2885fd480bb2db28254f8460e65cf78c6adab1: M
33a0ecc72567132af8fb5a204a4bbd162ab4476e: A A
8f86c2379330f5d8606ebee11faba3a3469cf24f: A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A 

In [ ]:
"""
diff --git b/file1.txt a/file1.txt
new file mode 100644
index 0000000000000000000000000000000000000000..be2348c3d866b914c3a6e7d6c555bb5d7bd304bc
--- /dev/null
+++ a/file1.txt
@@ -0,0 +1 @@
+random stuff in file1

diff --git b/file2.txt a/file2.txt
new file mode 100644
index 0000000000000000000000000000000000000000..418e1293379426f4cbbac7faec06d10783e433dd
--- /dev/null
+++ a/file2.txt
@@ -0,0 +1 @@
+random stuff in file2.txt
diff --git b/file1.txt a/file3.txt
similarity index 100%
rename from file1.txt
rename to file3.txt

diff --git b/file3.txt a/file3.txt
index be2348c3d866b914c3a6e7d6c555bb5d7bd304bc..c823b19ce6a339cd8245783669a0c0d55bd94528 100644
--- b/file3.txt
+++ a/file3.txt
@@ -1 +1 @@
-random stuff in file1
+random stuff in file3.txt
diff --git b/file4.txt a/file4.txt
new file mode 100644
index 0000000000000000000000000000000000000000..06c33614449231211067102407f59cdfaaecd969
--- /dev/null
+++ a/file4.txt
@@ -0,0 +1 @@
+some random stuff in file4.txt

diff --git b/file2.txt a/file2.txt
deleted file mode 100644
index 418e1293379426f4cbbac7faec06d10783e433dd..0000000000000000000000000000000000000000
--- b/file2.txt
+++ /dev/null
@@ -1 +0,0 @@
-random stuff in file2.txt
diff --git b/file5.txt a/file5.txt
new file mode 100644
index 0000000000000000000000000000000000000000..e69de29bb2d1d6434b8b29ae775ad8c2e48c5391

diff --git b/file4.txt a/file4.txt
deleted file mode 100644
index 06c33614449231211067102407f59cdfaaecd969..0000000000000000000000000000000000000000
--- b/file4.txt
+++ /dev/null
@@ -1 +0,0 @@
-some random stuff in file4.txt
diff --git b/file6.txt a/file6.txt
new file mode 100644
index 0000000000000000000000000000000000000000..7572d73dde61720d2c8742e4af924ad7a1bb1d18
--- /dev/null
+++ a/file6.txt
@@ -0,0 +1,2 @@
+random stuff in file4.txt
+this file will be renamed to file6.txt in this commit

diff --git b/file6.txt a/file7.txt
similarity index 97%
rename from file6.txt
rename to file7.txt
index 7572d73dde61720d2c8742e4af924ad7a1bb1d18..92f420a9cbfaa9be9966a12abb312f0d5d7c4423 100644
--- b/file6.txt
+++ a/file7.txt
@@ -1,2 +1,3 @@
 random stuff in file4.txt
 this file will be renamed to file6.txt in this commit
+a
-a

"""
# print(text.decode('utf-8')) 
# line 415 in /Users/Beaver/anaconda3/lib/python3.5/site-packages/git/diff.py

In [21]:
import numpy as np
from numpy import linalg as LA
w, v = LA.eig(np.diag((1, 0.5, 0.5)))

In [22]:
v

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [23]:
w

array([ 1. ,  0.5,  0.5])

In [24]:
LA.eig(np.array([[0, 0.33, 0.33, 0.33], [0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 0, 1]]))

(array([ 0.,  0.,  0.,  1.]),
 array([[  1.00000000e+000,  -1.00000000e+000,  -1.00000000e+000,
           4.96235926e-001],
        [  0.00000000e+000,   1.21464749e-291,   0.00000000e+000,
           5.01248410e-001],
        [  0.00000000e+000,   0.00000000e+000,   1.21464749e-291,
           5.01248410e-001],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           5.01248410e-001]]))

In [ ]:
class 